name: Chocolatey installation test
run-name: ${{ github.actor }} is testing the chocolatey installation of gopass-jsonapi 🚀

on:
  push:
    branches:
      - 'main'
    paths:
      - gopass-jsonapi/**
      - .github/workflows/chocolatey_installation.yml
  pull_request:
    branches:
      - 'main'
    paths:
      - gopass-jsonapi/**
      - .github/workflows/chocolatey_installation.yml

jobs:
  choco_install_with_config:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Choco install googlechrome
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install googlechrome --no-progress -ignore-checksums -y
      - name: Choco install gopass
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install gopass --no-progress
      - name: Run gopass setup
        run: gopass setup --crypto plain --storage fs
      - name: Choco install gopass-jsonapi
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install gopass-jsonapi\gopass-jsonapi.nuspec --no-progress --pre --params "'/Configure:true'"
      - name: Upload choco logs on failure
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: choco-logs
          path: 'C:\ProgramData\chocolatey\logs\chocolatey.log'
  choco_install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Choco install gopass-jsonapi
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install gopass-jsonapi\gopass-jsonapi.nuspec --no-progress --pre
      - name: Upload choco logs on failure
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: choco-logs
          path: 'C:\ProgramData\chocolatey\logs\chocolatey.log'
