name: markdownlint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Run mdl
      uses: actionshub/markdownlint@main
